### PR TITLE
Path updates

### LINKED ISSUE #16: make references to metadata repo relative rather than absolute
make references to files in NSDSLab-NWB-metadata relative rather than absolute

(for now it is assumed that you cloned the metadata repo under your `~/Src/`)

### PR DESCRIPTION
**Pull request by JesseLivezey**
Closes #16

This is unfortunately a fairly large PR that touches a lot of files and functions. It is meant to do the following things

- Define and create standardized variables and defaults for the `data_path`, `metadata_lib_path`, and `stim_lib_path`
- Standardize the use of `block_name` (`RFLYY_BXX`) as argument rather than `animal_name`, `block`, etc. Everything can be derived from `block_name`
- Update `generate_nwb.py` and anything it uses to be consistent with the above (there may still be inconsistencies in code this doesn't touch)
- Some documentation of conventions that we can refer back to.

I've tested this on 1 legacy block (R67_B2), and it makes it to stimulus/mark loading, which I believe is as far as things went before.

### CODE REVIEW

**Review by jihyunbak — COMMENTED** [review]
Commenting on `scripts/generate_nwb.py`: Having the argparse feature is a great idea! On the other hand, I think it is also helpful to explicitly keep a "ready to run" sample script, pointing to a test dataset.
We could keep both types of scripts here, or maybe we could move this new script to the `nwb_build` module (by adding an `if __name == '__main__' …` block). How do you think?

**Comment by jihyunbak** [comment]
Otherwise all looks good to me!

**Comment by JesseLivezey** [comment]
@jihyunbak I'll set argparse defaults so that the old block gets run by default if nothing is passed. Can probably have the best of both!

**Review by jihyunbak — APPROVED** [review]
Yes, this looks great! (Side note: I actually like `block_name` better than `block_folder`, I think it feels more intuitive from an end user's viewpoint … but we can make this a separate discussion)

**Comment by JesseLivezey** [comment]
Yeah, I like `block_name` as well, but distinguishing `RFLYY_BXX`, `BXX`, and `XX` is tricky! Too much compositionality! 😂 I'd probably go with `block_name` if `BXX` didn't exist.

**Pull request merged**
