### PR TITLE
devices and electrodes work

### LINKED ISSUE #81: store all relevant device metadata in NWB
potentially useful device metadata are currently ignored in the NWB conversion process, including:

- location details
- bad channels
- `n_columns`, `n_rows`, `orientation`
- xspacing, yspacing
- poly_neighbors (legacy metadata)
- …

we could keep these by flattening into text descriptions, at least.

### PR DESCRIPTION
**Pull request by jihyunbak**
# Description and related issues

- use `ElectrodesOriginator` to create NWB device objects, electrode groups, as well as single electrodes (dropping previous `DeviceOriginator` and `ElectrodeGroupOriginator` classes)
- keep device/electrode metadata that were previously ignored, by putting into text descriptions
- handle channel (electrode) mapping in MetadataManager, instead of ElectrodeOriginator as before — this simplifies table region generation and other electrode metadata indexing (specifically, `poly_neighbors` and `bad_chs`)
- add electrode coordinates to `rel_x, rel_y, rel_z` instead of `x, y, z` (use `np.nan` for the absolute xyz)
- fix formatting to pass flake8 check (just the files that are changed in this PR)

Closes #81 

# Checklist:

- [ ] All tests pass on catscan: run `pytest --basetemp=tmp -sv -n 8 tests` on catscan from the root directory
- [x] If needed, docs have been update: `docs/source` has been updated for any added, moved, or removed files
- [x] Docs build with no errors: run `make clean & make html` from the `docs` folder
- [ ] No python formatting errors: run `flake8 nsds_lab_to_nwb tests` from the root directory
    - [x] no formatting errors from the following:
        ```
        flake8 nsds_lab_to_nwb/metadata/
        flake8 nsds_lab_to_nwb/common/
        flake8 nsds_lab_to_nwb/components/electrode/
        flake8 nsds_lab_to_nwb/components/neural_data/
        ```

### CODE REVIEW

**Comment by jihyunbak** [comment]
@jthermiz Do you think we should use `rel_x`, `rel_y`, `rel_z` instead of `x`, `y`, `z` when we add `ch_pos` to electordes, and use some dummy values like 0.0 for the requred x,y,z? Would this help to resolve our issue #56 ? The `ch['x'], …` values are the channel coordinates in the probe metadata file.

pointer to current code:
https://github.com/BouchardLab/nsds_lab_to_nwb/blob/87431d55bd1f2b96faf8871b45819daf811dfcfb/nsds_lab_to_nwb/components/electrode/electrodes_originator.py#L46-L54

some references I've been looking at:
- [PyNWB API documentation for `add_electrode`](https://pynwb.readthedocs.io/en/stable/pynwb.file.html#pynwb.file.NWBFile.add_electrode)
- [the NWB "best practices" document](https://www.nwb.org/best-practices/#times)
- [ElectrodeCreator in Frank Lab rec-to-nwb](https://github.com/LorenFrankLab/rec_to_nwb/blob/master/rec_to_nwb/processing/nwb/components/electrodes/electrode_creator.py) (where they use 0.0 for the absolute x,y,z)

**Comment by jthermiz** [comment]
Based on the pynwb documentation, that seems like the way to go. But my
only concern would be if other packages actually follow this standard or if
they naively rely on x,y,z instead of x_rel, y_rel, z_rel. If you can
create an nwb with rel coordinates, I can see if spikeinterface correctly
reads in the electrode geometry.

**Comment by jihyunbak** [comment]
Updated to store electrode coordinates as relative xyz. Ready for review.

**Review by jthermiz — APPROVED** [review]
I tested this out and generated a nwb with rel electrode coordinates. I then passed this to spikeinterface and it read the rel coordinate correctly, so I'm good with this PR

**Comment by jihyunbak** [comment]
Thanks for testing this John!! Merging this PR

**Pull request merged**
