### PR TITLE
Add weight

### PR DESCRIPTION
**Pull request by jthermiz**
Add weight and 'g' to indicate grams. This works on the tdt pipeline. I have not yet tested with the htk pipeline

### CODE REVIEW

**Comment by jthermiz** [comment]
This addresses #53

**Comment by jihyunbak** [comment]
@jthermiz Thanks for this! I have one suggestion - it would be nice if all metadata validation/fix happened within MetadataManager, so that all we need to care about in NWBBuilder is to extract using correct metadata keys.

Specifically, I suggest that we modify `MetadataManager.__check_subject()`. There, check if the weight metadata is a string that ends with 'g' (for now assuming that the unit is always gram), and if not, append 'g' !

**Comment by jihyunbak** [comment]
Separately, I think eventually we want to do `subject=Subject(**self.metadata['subject']), ...` when we inject the subject metadata into the NWB content, near L148 of `nwb_builder.py`. To do that we need to fix the key `subject id` to `subject_id` in metadata. This could be a separate issue - no need to address in this PR.

**Comment by jihyunbak** [comment]
PR #74 can replace this, unless there is something else you want to do in this PR @jthermiz

**Comment by jthermiz** [comment]
That sounds good. I'm closing this PR

**Pull request closed without merging**
