### PR TITLE
move HTK and TDT tools

### PR DESCRIPTION
**Pull request by jihyunbak**
# Description and related issues

Move HTK and TDT readers from `nsds_lab_to_nwb.components` to a new subpackage `nsds_lab_to_nwb.tools`.

No linked issues.

# Checklist:

- [ ] All tests pass on catscan: run `pytest --basetemp=tmp -sv -n 8 tests` on catscan from the root directory
    - same failure mode as before
- [x] If needed, docs have been update: `docs/source` has been updated for any added, moved, or removed files
- [x] Docs build with no errors: run `make clean & make html` from the `docs` folder
- [ ] No python formatting errors: run `flake8 nsds_lab_to_nwb tests` from the root directory

### CODE REVIEW

**Comment by jihyunbak** [comment]
This is a suggestion - we can easily revert. Let me know if you feel we'd better keep the original structure (htk and tdt within `components`) or rename the new subpackage to something other than `tools`!

The rationale was that `components` are for the actual NWB components in our use case, while `tools` has more generic-purpose data reader classes that is not our lab specific.

**Review by jthermiz — APPROVED** [review]
That's fine by me

**Comment by jihyunbak** [comment]
Thanks @jthermiz !

**Comment by jihyunbak** [comment]
Since this is more of a organizational choice than a functional fix, I'll wait for your response as well @JesseLivezey

**Comment by JesseLivezey** [comment]
Seems like a good change to me!

**Pull request merged**
